using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Shared
{
    public  class AutogeneratedAlphanumericCode
    {
        /// <summary>
        /// Generate alphanumeric code for booking number.
        /// </summary>
        /// <returns></returns>
        public string GenerateAlphaNumeric()
        {
            string alphabets = "ABCDEFGHIJKLMNOPQRSTUVWXYZ";
            string small_alphabets = "abcdefghijklmnopqrstuvwxyz";
            string numbers = "1234567890";

            string characters = numbers;
            
                characters += alphabets + small_alphabets + numbers;
            
            
            string alphanumeric = string.Empty;
            for (int i = 0; i < 8; i++)
            {
                string character = string.Empty;
                do
                {
                    int index = new Random().Next(0, characters.Length);
                    character = characters.ToCharArray()[index].ToString();
                } while (alphanumeric.IndexOf(character) != -1);
                alphanumeric += character;
            }
             return alphanumeric;
        }
    }
}
