//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookingDetail
    {
        public int OrderId { get; set; }
        public int CampId { get; set; }
        public int TotalDays { get; set; }
        public string ContactNo { get; set; }
        public string BillAddress { get; set; }
        public System.DateTime CheckIn { get; set; }
        public System.DateTime CheckOut { get; set; }
        public int Amount { get; set; }
        public string BookingNo { get; set; }
        public string State { get; set; }
        public string Country { get; set; }
        public string ZIP { get; set; }
    
        public virtual Camp Camp { get; set; }
    }
}
